/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import controller.Controller;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import Model.Parfum;
import Model.Prosentase_Alkohol;
import Model.Transaksi;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author ASUS
 */
public class transaksiview extends javax.swing.JFrame {
    
    Controller prfm;
    private Integer total_harga;
    private Integer Kembali;
   

    /**
     * Creates new form transaksiview
     * @throws java.sql.SQLException
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @throws java.sql.SQLException
     */
    @SuppressWarnings("unchecked")
    public transaksiview() throws SQLException {
        
        initComponents();
        this.prfm  = new Controller();
        this.showTable1();
        this.showComboBox1();
        this.showComboBox2();
        
    }
    public void showTotalharga(){
        Total_hrg.setText(total_harga.toString());
    }
    public void showKembali(){
        kembali.setText(Kembali.toString());
    }
    private void showTable1() throws SQLException{
        DefaultTableModel dt = new DefaultTableModel(new String[]{
            "ID_TRANSAKSI","NAMA_PARFUM","VOLUME_ALKOHOL"
        }, 0);
        dt.setRowCount(0);
        
        for (Transaksi p : this.prfm.getDataTransaksi()){
            dt.addRow(new String[]{
              p.getId_transaksi().toString(),
              p.getParfum().getNama_Parfum(),
              p.getProsentase_alkohol().getVolume_alkohol().toString(),
              
            });
            }
        this.jTable1.setModel(dt);
        }
    public void showComboBox1() throws SQLException{
        
        DefaultComboBoxModel a = new DefaultComboBoxModel();
            for (Parfum parfum :this.prfm.getDataParfum()){
                a.addElement(parfum.getNama_Parfum());
            }
            this.Cb1.setModel(a);
    }
    public void showComboBox2() throws SQLException{
        
        DefaultComboBoxModel b = new DefaultComboBoxModel();
            for (Prosentase_Alkohol prosentase_alkohol :this.prfm.getDataProsentase_Alkohol()){
                b.addElement(prosentase_alkohol.getVolume_alkohol());
            }
            this.Cb2.setModel(b);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Total_hrg = new javax.swing.JTextField();
        jsimpan = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        Id_transaksi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_transaksi = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        struk = new javax.swing.JTextArea();
        print = new javax.swing.JButton();
        tgl_transaksi = new javax.swing.JTextField();
        Uang_byr = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Cb1 = new javax.swing.JComboBox<>();
        Cb2 = new javax.swing.JComboBox<>();
        kembali = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TRANSAKSI");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAMA_PARFUM");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VOL_PROSENTASE_ALKOHOL");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TGL_TRANSASKSI");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TOTAL_HARGA");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("UANG_BAYAR");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("KEMBALIAN");

        Total_hrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_hrgActionPerformed(evt);
            }
        });

        jsimpan.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jsimpan.setText("Save");
        jsimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jsimpanMouseClicked(evt);
            }
        });
        jsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsimpanActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ID_TRANSAKSI");

        Id_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_transaksiActionPerformed(evt);
            }
        });

        tb_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_TRANSAKSI", "NAMA_PARFUM","VOLUME_ALKOHOL", "TGL_TRANSAKSI", "TOTAL_HARGA", "UANG_BAYAR", "KEMBALIAN"
            }
        ));
        jScrollPane1.setViewportView(tb_transaksi);

        struk.setColumns(20);
        struk.setRows(5);
        jScrollPane2.setViewportView(struk);

        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        tgl_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_transaksiActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        Cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb1ActionPerformed(evt);
            }
        });

        Cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Id_transaksi)
                            .addComponent(tgl_transaksi)
                            .addComponent(Total_hrg)
                            .addComponent(Uang_byr)
                            .addComponent(Cb1, 0, 230, Short.MAX_VALUE)
                            .addComponent(Cb2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kembali)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jsimpan)
                        .addGap(18, 18, 18)
                        .addComponent(print)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Uang_byr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jsimpan)
                            .addComponent(print))
                        .addGap(71, 71, 71))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(Id_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(Cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(Cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tgl_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Total_hrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(167, 167, 167))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(334, 334, 334))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 553, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tgl_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_transaksiActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        try{
        Transaksi tran = this.prfm.getDataTransaksi().get(this.tb_transaksi.getSelectedRow());
        String Teks = ("-------- STRUK PARFUM --------" + "\n"
            + "ID_ORDER             :" + tran.getId_transaksi().toString()+"\n"
            + "NAMA_PARFUM          : " + tran.getParfum().getNama_Parfum()+ "\n"
            + "VOLUME_ALKOHOL       : " + tran.getProsentase_alkohol().getVolume_alkohol().toString() + "\n"
            + "TANGGAL_TRANSAKSI    : " + tran.getTanggal_transaksi().toString()+ "\n"
            + "TOTAL_HARGA          : " + tran.getTotal_bayar()+ "\n"
            + "UANG_BAYAR           : " +tran.getUang_bayar()+ "\n"
            + "KEMBALIAN            :" +tran.getKembalian()+"\n"
            +"-----------------------------------------"+"\n"
        );
        this.struk.setText(Teks);
                } catch (SQLException ex) {
                  System.out.println(ex);
                }
        
    }//GEN-LAST:event_printActionPerformed

    private void Id_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_transaksiActionPerformed

    private void jsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsimpanActionPerformed
//Transaksi transaksi = new Transaksi();
//        try {
//            transaksi.setParfum(this.prfm.getDataParfum().get(this.Cb1.getSelectedIndex()));
//            transaksi.setProsentase_alkohol(this.prfm.getDataProsentase_Alkohol().get(this.Cb2.getSelectedIndex()));
//            transaksi.setTanggal_transaksi(new SimpleDateFormat("dd/MM/yyyy").parse(this.tgl_transaksi.getText()));
//            //transaksi.setBerat_cucian(Integer.parseInt(jfBerat.getText()));
//            Total_hrg += this.prfm.getDataParfum().get(Cb1.getSelectedIndex()).getHarga_Parfum()* Integer.parseInt(Cb1.getText());
//   
//            transaksi.setTotal_bayar(Total_hrg);
//            
//            transaksi.setUang_bayar(Integer.parseInt(Uang_byr.getText()));
//            kembali = Integer.parseInt(Uang_byr.getText()) - Integer.parseInt(Total_hrg.getText());
//            
//            transaksi.setKembalian(kembali);
//            this.prfm.insertTransaksi(transaksi);  
//            this.showTableTransaksi();
//            showTotalharga();
//            showKembali();
//            Total_hrg=0;
//            kembali =0;
//                 
//        } catch (SQLException | ParseException err) {
//            System.out.println(err);
//        }        
    }//GEN-LAST:event_jsimpanActionPerformed

    private void jsimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsimpanMouseClicked
         //TODO add your handling code here:
                DefaultTableModel dataModel = (DefaultTableModel) tb_transaksi.getModel();
                List list = new ArrayList<>();
                tb_transaksi.setAutoCreateColumnsFromModel(true);
                list.add(Id_transaksi.getText());
                list.add(Cb1.getSelectedItem());
                list.add(Cb2.getSelectedItem());
                list.add(tgl_transaksi.getText());
                list.add(Uang_byr.getText());
                list.add(Total_hrg.getText());
                list.add(kembali.getText());
                dataModel.addRow(list.toArray());
    }//GEN-LAST:event_jsimpanMouseClicked

    private void Total_hrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_hrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total_hrgActionPerformed

    private void Cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Cb1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(transaksiview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(transaksiview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(transaksiview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(transaksiview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new transaksiview().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(transaksiview.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cb1;
    private javax.swing.JComboBox<String> Cb2;
    public javax.swing.JTextField Id_transaksi;
    private javax.swing.JTextField Total_hrg;
    private javax.swing.JTextField Uang_byr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jsimpan;
    private javax.swing.JTextField kembali;
    private javax.swing.JButton print;
    private javax.swing.JTextArea struk;
    private javax.swing.JTable tb_transaksi;
    private javax.swing.JTextField tgl_transaksi;
    // End of variables declaration//GEN-END:variables
}